:openshift_version: 4.14.18

= OpenShift Disconnected Workshop

Welcome to the OpenShift Disconnected Workshop!

It's DISCO time! 💃🕺

In this workshop you will learn about, prepare for, install and operate an OpenShift 4 cluster in a disconnected network.
This is also known as installing OpenShift in a https://docs.openshift.com/container-platform/latest/installing/installing_aws/installing-restricted-networks-aws-installer-provisioned.html#installation-about-restricted-networks_installing-restricted-networks-aws-installer-provisioned[_restricted network_ or an _air gap network_].
The workshop environment (illustrated below) gives you access to several servers/systems in different networks. These instructions and environments were created using OpenShift version `{openshift_version}`.

[TIP]
--
The term _disconnected network_ can mean different things to different people.

This workshop describes one particular way of performing a disconnected installation.
Another way would be to setup, secure, and use a proxy server.
You could also install OpenShift with a temporary connection to the installation resources and remove the access later.
--

== Who uses disconnected networks?

Before we begin let's consider a few use-cases for disconnected networks:

* *Military & Law Enforcement*: Often need secure environments to handle sensitive data
* *Research organizations*: Want to protect their data / provide data governance
* *Industrial / utility*: Use https://en.wikipedia.org/wiki/SCADA[SCADA] networks to protect their supervisory and control networks

== Understanding our lab environment

The image below illustrates the various networks, systems, and connections this workshop provides.
The diagram will be simplifed and explained in more detail in later chapters.
The lab instructions will help you prepare the `jump` system to download the installation content, configure the `highside` system to host the content, and create the `openshift.disco.lab` cluster (it doesn't exist yet.)

The *salsa* network and its systems are built automically when the workshop environment is created.
You can log into the *salsa* systems to compare your systems with functioning disconnected systems.

image::disco-4.svg[disco diagram,800]

=== Lab Access and Documentation notes

The terminal window to your right is *already* logged into the [.lowside]#`jump`# system.
The right-hand side of this browser can also show the [.lowside]#`jump`# system's graphical desktop by clicking on the *Desktop* button.
The lab instructions should be run as the `{bastion_ssh_user_name}` user.

If you prefer to use your own terminal, you can log into the [.lowside]#`jump`# system using SSH like this:

[source,bash,role=execute,subs="attributes"]
----
# Your unique lab-user password is {bastion_ssh_password}
{bastion_ssh_command}
----

If you prefer to use your own VNC viewer, you can connect to the [.lowside]#`jump`# system's graphical desktop like this:

[source,bash,role=execute,subs="attributes"]
----
# Your unique lab-user password is {bastion_ssh_password}
# Your unique VNC password is also {bastion_ssh_password}
vncviewer -via {bastion_ssh_command} 127.0.0.1:0
----

//TODO - replace {bastion_ssh_command} with the correct variable