= Preparing the Installation

In this lab, we'll make final preparations and execute the OpenShift Installer.

image::disco-3.svg[disco diagram,800]

== Build the install-config.yaml

Here's a diagram describing the inputs and outputs of the installation configuration process: 

image::install-overview-disco.svg[Install Overview,800]

{counter:install}. Let's start by creating a workspace on the [.highside]#*highside* system# to house our installation materials:

[.highside,source,bash,role=execute,subs="attributes"]
----
mkdir /mnt/high-side-data/install
cd /mnt/high-side-data/install
----

Create an initial `install-config.yaml`:

[.highside,source,yaml,role=execute,subs="attributes"]
----
cat << EOF > /mnt/high-side-data/install/install-config.yaml
---
apiVersion: v1
metadata:
  name: disco
baseDomain: lab
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: {aws_default_region}
    subnets:
    - {PrivateSubnet1}
publish: Internal
additionalTrustBundlePolicy: Always
EOF
----

{counter:install}. Generate an SSH key pair for access to cluster nodes and add it to the `install-config.yaml`

[.highside,source,bash,role=execute,subs="attributes"]
----
ssh-keygen -C "OpenShift Debug" -N "" -f /mnt/high-side-data/id_rsa
echo "sshKey: $(cat /mnt/high-side-data/id_rsa.pub)" >> /mnt/high-side-data/install/install-config.yaml
----

[NOTE]
The SSH key for OpenShift is only used for troubleshooting.

{counter:install}. Use `jq` to minify your container registry pull secret and add it to the `install-config.yaml`

[.highside,source,bash,role=execute,subs="attributes"]
----
echo "pullSecret: '$(jq -c . $XDG_RUNTIME_DIR/containers/auth.json)'" >> /mnt/high-side-data/install/install-config.yaml
----

[NOTE]
--
For connected installations, you would use your _pull secret_ from the Hybrid Cloud Console, but for our use case, the `mirror-registry` is the only _image registry_ OpenShift will need to authenticate to.
--

=== Add `imageContentSources`

We will be using what was generated by `oc mirror` to ensure that the cluster install maps the container images to our disconnected mirror
running on the [.highside]#highside system#

*Before continuing*, make sure the second stage of your mirror is done by checking that the `imageContentSourcePolicy.yaml` file exists on disk.

// while true ; do if (test -e /mnt/high-side-data/oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml) ; then break; fi; sleep 5; done

[.highside,source,bash,role=execute,subs="attributes"]
----
if (test -e /mnt/high-side-data/oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml)
  then
     echo "Looks good, go ahead!"
   else
     echo "Uh oh, something is wrong..."
fi
----

Then you can append the relevant snippet to your `install-config.yaml` by running this command:

[.highside,source,bash,role=execute]
----
cat << EOF >> /mnt/high-side-data/install/install-config.yaml
imageContentSources:
$(grep "mirrors:" -A 2 --no-group-separator /mnt/high-side-data/oc-mirror-workspace/results-*/imageContentSourcePolicy.yaml)
EOF
----

They'll look something like this:

[source,yaml]
----
imageContentSources:
  - mirrors:
     - ip-10-0-51-206.ec2.internal:8443/openshift/release-images
     source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
     - ip-10-0-51-206.ec2.internal:8443/openshift/release
     source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
----

=== Trust mirror registry CA

Add the root CA of our mirror registry to the trust bundle using the `additionalTrustBundle` field by running this command:

[.highside,source,bash,role=execute]
----
cat << EOF >> /mnt/high-side-data/install/install-config.yaml
additionalTrustBundle: |
$(sed 's/^/  /' /home/lab-user/quay-install/quay-rootCA/rootCA.pem)
EOF
----

It should look something like this:

[source,yaml]
----
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
----

Then make a backup of your `install-config.yaml` since the installer will consume (and delete) it:

//TODO - the command block below wasn't rendering properly for jcall

[.highside,source,bash,role=execute,subs="attributes"]
----
cd /mnt/high-side-data/install
cp -v install-config.yaml install-config.yaml.backup
----

== Running the Installation

We're ready to run the install!
Let's kick off the cluster installation:

[NOTE]
--
The OpenShift Installer (`openshift-install`) is rebuilt for every release (`{openshift_version}`).

This means that you can't use `openshift-install` version `{openshift_min_version}` to install OpenShift `{openshift_max_version}`.
--


[.highside,source,bash,role=execute,subs="attributes"]
----
openshift-install create cluster --dir /mnt/high-side-data/install
----
[.output]
----
...
INFO Install complete!
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/mnt/high-side-data/install/auth/kubeconfig'
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.disco.lab
INFO Login to the console with user: "kubeadmin", and password: "password"
INFO Time elapsed: 30m49s
----

The installation process should take about 30 minutes.

[IMPORTANT]
This `disco.lab` cluster will take about 30 minutes to install but if you do not want to wait *proceed to the next section
to work on the pre-built salsa.lab cluster*!
