= The Disconnected Installation Process

Let's start with an overview of the disconnected installation process.
You can refer to the https://docs.openshift.com/container-platform/latest/installing/disconnected_install/index.html[OpenShift documentation] for more information.
The basic steps are:

1. Prepare a system ([.lowside]#jump#) that can download the installation content
** This system uses `oc-mirror` to download the content
2. Prepare a system ([.highside]#highside#) that can _serve_ the installation content in the disconnected network
** This system uses `oc-mirror` to populate the `mirror-registry` 
3. Move the content from the [.lowside]#jump# system to the [.highside]#highside# system
** `rsync` in this workshop
** many people uses DVDs and actually walk the content between systems (aka https://en.wikipedia.org/wiki/Sneakernet[_sneaker net_] 👟)
4. Tell the OpenShift installation program (`openshift-install`) where to find the installation content
** Make a few changes the `install-config.yaml` file (aka the "answer file")
5. Modify some settings after OpenShift has been installed
** e.g. where to look for apps/Operators and updates

== Preparing the `jump` system

The [.lowside]#jump system# lives in the *lowside* network which allows it to access resources on the public internet.
The network is called *lowside* because it has a low security profile, and shouldn't be used to store sensitive information.

image::disco-0.svg[disco diagram,800]

=== Downloading Tooling

Let's grab the tools we need for the [.highside]#highside system# - we will also be using some of them on the [.lowside]#jump system#. 

[NOTE]
The OpenShift tooling is built for every release and version data is encoded in each binary.

Before we begin, `cd` into the `/mnt/low-side-data/` directory:
[.lowside,source,bash,role=execute,subs="attributes"]
----
cd /mnt/low-side-data/
----

Then download the following tools:

 ** `oc`: OpenShift CLI

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/openshift-client-linux.tar.gz
tar -xzf oc.tar.gz oc
rm -f oc.tar.gz
sudo cp oc /bin
----

 ** `oc-mirror`: oc plugin for mirorring release, operator, and helm content

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc-mirror.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/oc-mirror.tar.gz
tar -xzf oc-mirror.tar.gz
rm -f oc-mirror.tar.gz
chmod +x oc-mirror
sudo cp oc-mirror /bin
----

 ** `mirror-registry`: small-scale Quay registry designed for mirroring

[.lowside,source,bash,role=execute]
----
curl -L -o mirror-registry.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
tar -xzf mirror-registry.tar.gz
rm -f /mnt/low-side-data/mirror-registry.tar.gz
----

 ** `openshift-installer`: OpenShift Installer

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o openshift-installer.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/openshift-install-linux.tar.gz
tar -xzf openshift-installer.tar.gz openshift-install
rm -f openshift-installer.tar.gz
----

== Mirroring Content to Disk

The `oc-mirror` plugin supports mirroring content directly from upstream sources to a mirror registry, but since there is an air gap between our low side and high side, that's not an option for this lab.
Instead, we'll mirror content to a tarball on disk that we can then sneaker net into the [.highside]#highside system# on the high side.
We'll then mirror from the tarball into the mirror registry from there.

{counter:mirror}. We will need an OpenShift pull secret to authenticate to the Red Hat registries. Grab yours from the https://console.redhat.com/openshift/install/pull-secret[Hybrid Cloud Console,window=_blank].

[NOTE]
If you cannot get a pull secret from the Red Hat Hybrid Cloud Console, you can find one at `~/pull-secret-example.json`

[.lowside,source,bash,role=execute]
----
mkdir ~/.docker
cp pull-secret.json ~/.docker/config.json
----

{counter:mirror}. Next, we need to create a `ImageSetConfiguration` that describes the parameters of our mirror.

{counter:mirror}. To save time and storage, we're going to omit the operator catalogs and mirror only the release images.

We'll still get a fully functional cluster, but *OperatorHub* will be empty. You'll want to have a strategy for mirroring operator content in a real world scenario.

We'll also include an `ubi` image so we can run some tests later.
Create a file called `imageset-config.yaml` with the following contents:

[.lowside,source,yaml,subs="attributes",role=execute]
----
cat << EOF > /home/lab-user/imageset-config.yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: {openshift_channel}
      type: ocp
      minVersion: {openshift_version}
      maxVersion: {openshift_version}

  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: web-terminal
      channels:
      - name: fast
  
  additionalImages:
  - name: registry.redhat.io/ubi8/nginx-120
EOF
----

{counter:mirror}. Now we're ready to kick off the mirror!
This should take a few minutes to complete.

[.lowside,source,bash,role=execute]
----
oc mirror --config imageset-config.yaml file:///mnt/low-side-data
----
[.output]
----
...
info: Mirroring completed in 2m52.23s (131.9MB/s)
Creating archive /mnt/low-side-data/mirror_seq1_000000.tar
----
