= Preparing the High Side

In this lab, we'll prepare the High Side.
Recall from our architecture diagram that our bastion server on the high side will host our mirror registry.
To do this we're interested in using `podman`, since it simplifies operation of the registry to run it within a container.

However, we have a dilemma: the AMI we used for the prep system does not have `podman` installed!
Unfortunately, `podman` cannot be sneakernetted into the bastion server as we're doing with other tools, because the installation requires a number of dependencies.

To solve this problem, most customers either _build a custom RHEL image_ with `podman` pre-installed, *or* create a firewall exception in the high side to enable access to a content repository, like https://access.redhat.com/articles/4720861[RHUI] (Red Hat Update Infrastructure).
Recall from xref:lab02.adoc[Lab 2] that RHUI is part of our squid proxy's allowed list, so we've opted for the latter approach here. In fact, we've pre-installed `podman` on your bastion server during the lab creation.

== Accessing the High Side

Now we need to access our bastion server on the high side.
In real customer environments, this might entail use of a VPN, or physical access to a workstation in a secure facility such as a SCIF.
To make things a bit simpler for our lab, we're going to restrict access to our bastion to its _private IP address_.
So we'll use the prep system as a sort of bastion-to-the-bastion.
+
If your mirror is still running, you'll need to wait for it to complete before you continue. Once it's done, SSH into from the prep system over to the bastion server:
+
[source,bash,role=execute,subs="attributes"]
----
ssh lab-user@{HighSideInstancePrivateIp}
{bastion_ssh_password}
----

== Prove we do not have internet access

Let's check that we have no Internet access:
+
[source,bash,role=execute]
----
curl google.com
----
+
Your output will contain something like this:
+
[source,html]
----
...
<blockquote id="error">
<p><b>Access Denied.</b></p>
</blockquote>

<p>Access control configuration prevents your request from being allowed at this time. Please contact your service provider if you feel this is incorrect.</p>

<p>Your cache administrator is <a href="mailto:root?subject=CacheErrorInfo%20-%20ERR_ACCESS_DENIED&amp;body=CacheHost%3A%20squid%0D%0AErrPage%3A%20ERR_ACCESS_DENIED%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Thu,%2006%20Jul%202023%2013%3A45%3A11%20GMT%0D%0A%0D%0AClientIP%3A%2010.0.52.68%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2F%20HTTP%2F1.1%0AUser-Agent%3A%20curl%2F7.61.1%0D%0AAccept%3A%20*%2F*%0D%0AHost%3A%20google.com%0D%0A%0D%0A%0D%0A">root</a>.</p>
<br>
...
----
+
This response comes from the squid proxy in the NAT server, and it's blocking the request because google.com is not part of the allowed list. Let's go back to the prep system to start the sneakernet:
+
[source,bash,role=execute,subs="attributes"]
----
exit
----

== Sneakernetting Content to the High Side

We'll now deliver the high side gift basket to the bastion server.

Let's send over our payload and store it in `/mnt/high-side-data` on the bastion:
+
[source,bash,role=execute,subs="attributes"]
----
rsync -avP /mnt/low-side-data/ lab-user@{HighSideInstancePrivateIp}:/mnt/high-side-data/
{bastion_ssh_password}
----

== Creating a Mirror Registry

Images used by operators and platform components must be mirrored from upstream sources into a container registry that is accessible by the high side.
You can use any registry you like for this as long as it supports Docker v2, such as:

* Red Hat Quay
* JFrog Artifactory
* Sonatype Nexus Repository
* Harbor

An OpenShift subscription includes access to the https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-creating-registry.html#installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift], which is a small-scale container registry designed specifically for mirroring images in disconnected installations.
We'll make use of this option in this lab.

Mirroring all release and operator images can take awhile depending on the network bandwidth.
For this lab, recall that we're going to mirror just the release images to save time and resources.

We should have the `mirror-registry` binary along with the required container images available on the bastion in `/mnt/high-side-data`.

First, let's SSH back into the bastion from the prep system:

[source,bash,role=execute,subs="attributes"]
----
ssh lab-user@{HighSideInstancePrivateIp}
{bastion_ssh_password}
----

And kick off our install:

[source,bash,role=execute]
----
cd /mnt/high-side-data
./mirror-registry install --quayHostname $(hostname) --quayRoot /mnt/high-side-data/quay/quay-install --quayStorage /mnt/high-side-data/quay/quay-storage --pgStorage /mnt/high-side-data/quay/pg-data --initPassword discopass
----

If all goes well, you should see something like:

[source,bash,role=execute]
----
INFO[2023-07-06 15:43:41] Quay installed successfully, config data is stored in /mnt/quay/quay-install
INFO[2023-07-06 15:43:41] Quay is available at https://ip-10-0-51-47.ec2.internal:8443 with credentials (init, discopass)
----

Copy the CA into the root trust

[source,bash,role=execute]
----
sudo cp /mnt/high-side-data/quay/quay-install/quay-rootCA/rootCA.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust
----

Login to the registry with `podman`.
This will generate an auth file at `/run/user/1000/containers/auth.json`:

[source,bash,role=execute]
----
podman login -u init -p discopass $(hostname):8443
----

== Mirroring Content

Now we're ready to mirror images from disk into the registry.
Let's add `oc` and `oc-mirror` to the path:

[source,bash,role=execute]
----
sudo mv /mnt/high-side-data/oc /bin/
sudo mv /mnt/high-side-data/oc-mirror /bin/
----

And fire up the mirror!
Let's send it to the background with `nohup` so we can get to work on the installation prep while this is running:

[source,bash,role=execute]
----
nohup oc mirror --from=/mnt/high-side-data/mirror_seq1_000000.tar docker://$(hostname):8443 &
----

Press `ENTER` once more to get your prompt back.
The log output will be streamed to a file called `nohup.out`, and your shell will notify you when the process has been completed after 10 minutes or so.

With the final mirror now running, there are only a few steps left to prepare the cluster installation.
Let's get to it!
