:openshift_version_channel: stable-4.14
:openshift_version: 4.14.19

= The Disconnected Installation Process

Let's start with an overview of the disconnected installation process.
You can refer to the https://docs.openshift.com/container-platform/latest/installing/disconnected_install/index.html[OpenShift documentation] for more information.
The basic steps are:

1. Prepare a system (`jump`) that can download the installation content
** This system uses `oc-mirror` to download the content
2. Prepare a system (`highside`) that can _serve_ the installation content in the disconnected network
** This system uses `oc-mirror` to populate the `mirror-registry` 
3. Move the content from the `jump` system to the `highside` system
** `rsync` in this workshop
** many people uses DVDs and actually walk the content between systems (aka https://en.wikipedia.org/wiki/Sneakernet[_sneaker net_] 👟)
4. Tell the OpenShift installation program (`openshift-install`) where to find the installation content
** Make a few changes the `install-config.yaml` file (aka the "answer file")
5. Modify some settings after OpenShift has been installed
** e.g. where to look for apps/Operators and updates

== Preparing the Low Side

A disconnected installation begins by downloading the `oc-mirror` tool and installation content to a system we refer to as the `jump` system.
In this workshop environement the  that has outbound access to the Internet.
This server resides in a network environment commonly referred to as the *Low Side* due to its low security profile.
Compliance requirements usually prevent the low side from housing sensitive data or private information.

// TODO remove the "glue" when I copied lab04 into lab02
== GLUE

== Preparing the Low Side

In this lab, we will prepare the low side.

== Accessing the Prep System

Now that our prep system is up, let's SSH into it and download the content

* {bastion_ssh_command} 
* {bastion_ssh_password}

== Downloading Tooling

Let's grab the tools we'll need for the [.highside]#*highside* system# - we will also be using some of them on the [.lowside]#*jump* system#. 
Before we begin, `cd` into the `/mnt/low-side-data/` directory:
[.lowside,source,bash,role=execute,subs="attributes"]
----
cd /mnt/low-side-data/
----

Then download the following tools:

 ** `oc`: OpenShift CLI

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/openshift-client-linux.tar.gz
tar -xzf oc.tar.gz oc
rm -f oc.tar.gz
sudo cp oc /bin
----

 ** `oc-mirror`: oc plugin for mirorring release, operator, and helm content

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc-mirror.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/oc-mirror.tar.gz
tar -xzf oc-mirror.tar.gz
rm -f oc-mirror.tar.gz
chmod +x oc-mirror
sudo cp oc-mirror /bin
----

 ** `mirror-registry`: small-scale Quay registry designed for mirroring

[.lowside,source,bash,role=execute]
----
curl -L -o mirror-registry.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
tar -xzf mirror-registry.tar.gz
rm -f /mnt/low-side-data/mirror-registry.tar.gz
----

 ** `openshift-installer`: OpenShift Installer

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o openshift-installer.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_version}/openshift-install-linux.tar.gz
tar -xzf openshift-installer.tar.gz openshift-install
rm -f openshift-installer.tar.gz
----

== Mirroring Content to Disk

The `oc-mirror` plugin supports mirroring content directly from upstream sources to a mirror registry, but since there is an air gap between our low side and high side, that's not an option for this lab.
Instead, we'll mirror content to a tarball on disk that we can then sneaker net into the *highside* system on the high side.
We'll then mirror from the tarball into the mirror registry from there.

{counter:mirror}. We'll first need an OpenShift pull secret to authenticate to the Red Hat registries.
If you're in a guided workshop, your instructor may provide this for you.
Otherwise, grab your own from the https://console.redhat.com/openshift/install/pull-secret[Hybrid Cloud Console].

[.lowside,source,bash,role=execute]
----
mkdir ~/.docker
cp pull-secret.txt ~/.docker/config.json
----

{counter:mirror}. Next, we need to create a `ImageSetConfiguration` that describes the parameters of our mirror.

{counter:mirror}. To save time and storage, we're going to omit the operator catalogs and mirror only the release images.

We'll still get a fully functional cluster, but *OperatorHub* will be empty. You'll want to have a strategy for mirroring operator content in a real world scenario.

We'll also include an `ubi` image so we can run some tests later.
Create a file called `imageset-config.yaml` with the following contents:

[source,yaml,subs="attributes"]
----
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: {openshift_version_channel}
      type: ocp
      minVersion: {openshift_version}
      maxVersion: {openshift_version}

  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: web-terminal
      channels:
      - name: fast
  
  additionalImages:
  - name: registry.redhat.io/ubi8/nginx-120
----

. Now we're ready to kick off the mirror!
This should take a few minutes to complete.

[.lowside,source,bash,role=execute]
----
oc mirror --config imageset-config.yaml file:///mnt/low-side-data
----