= Preparing the High Side

In this lab, we'll prepare the High Side.
Recall from our architecture diagram that our *highside* system on the high side will host our mirror registry.
To do this we're interested in using `podman`, since it simplifies operation of the registry to run it within a container.

[TIP]
We need `podman` installed on the *highside* system. For this lab, recall from xref:lab02.adoc[Lab 2] that the AWS Red Hat Update Infrastructure is part of our squid proxy's allowed URL list
and that `podman` has been preinstalled for you.

image::disco-2.svg[disco diagram,800]

== Accessing the High Side

Now we need to access our *highside* system on the high side.
In real customer environments, this might entail use of a VPN, or physical access to a workstation in a secure facility such as a SCIF.

// TODO not sure what we are saying here?
// To make things a bit simpler for our lab, we're going to restrict access to *highside* to its _private IP address_.
// So we'll use the prep system as a sort of bastion-to-the-bastion.

If your mirror is still running, you'll need to wait for it to complete before you continue. Once it's done, SSH into from the *jump* system over to the *highside* system:

[WARNING]
Ensure that your mirror command `oc mirror` has completed successfully before proceeding in the lab.

First, copy your SSH key to the *highside* system

[.lowside,source,bash,role=execute,subs="attributes"]
----
ssh-copy-id highside
{bastion_ssh_password}
----

Then test it with SSH

[.lowside,source,bash,role=execute,subs="attributes"]
----
ssh lab-user@highside
----

== Prove we do not have internet access

Check that we do not have Internet access:

[.highside,source,bash,role=execute]
----
curl -vso /dev/null google.com
----

Your output will contain something like this:

[source,html]
----
...
< HTTP/1.1 403 Forbidden
< Server: squid/5.5
< Mime-Version: 1.0
< Date: Tue, 23 Apr 2024 23:44:53 GMT
< Content-Type: text/html;charset=utf-8
< Content-Length: 3432
< X-Squid-Error: ERR_ACCESS_DENIED 0
< Vary: Accept-Language
< Content-Language: en
< X-Cache: MISS from squid
< X-Cache-Lookup: NONE from squid:3128
< Via: 1.1 squid (squid/5.5)
< Connection: keep-alive
...
----

This response comes from the squid proxy in the NAT server, and it's blocking the request because google.com is not part of the allowed list. Let's go back to the *jump* system to start the sneakernet:

[.highside,source,bash,role=execute,subs="attributes"]
----
exit
----

== Moving Content to the High Side

We'll now deliver the high side gift basket. Let's send over our payload and store it in `/mnt/high-side-data` on the *highside* system:

[.lowside,source,bash,role=execute,subs="attributes"]
----
rsync -avP /mnt/low-side-data/ lab-user@highside:/mnt/high-side-data/
----

== Creating a Mirror Registry

Images used by operators and platform components must be mirrored from upstream sources into a container registry that is accessible by the high side.

An OpenShift subscription includes access to the https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-creating-registry.html#installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift], which is a small-scale container registry designed specifically for mirroring images in disconnected installations.
We'll make use of this option in this lab.

[NOTE]
--
You can use any registry you like for this as long as it supports Docker v2, such as:

* Red Hat Quay
* JFrog Artifactory
* Sonatype Nexus Repository
* Harbor
--

Mirroring all release and operator images can take some time depending on the network bandwidth.
For this lab, recall that we are only mirroring the release images to save time and resources.

We should have the `mirror-registry` binary along with the required container images available on *highside* in `/mnt/high-side-data`.

First, let's SSH back into the *highside* system:

[.lowside,source,bash,role=execute,subs="attributes"]
----
ssh lab-user@highside
----

And kick off our mirror registry install:

[.highside,source,bash,role=execute]
----
cd /mnt/high-side-data
./mirror-registry install --quayHostname $(hostname) --quayRoot /mnt/high-side-data/quay/quay-install --quayStorage /mnt/high-side-data/quay/quay-storage --pgStorage /mnt/high-side-data/quay/pg-data --initPassword discopass
----

If all goes well, you should see something like:

[source,bash,role=execute]
----
INFO[2023-07-06 15:43:41] Quay installed successfully, config data is stored in /mnt/quay/quay-install
INFO[2023-07-06 15:43:41] Quay is available at https://ip-10-0-51-47.ec2.internal:8443 with credentials (init, discopass)
----

Copy the CA into the root trust

[.highside,source,bash,role=execute]
----
sudo cp /mnt/high-side-data/quay/quay-install/quay-rootCA/rootCA.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust
----

Login to the registry with `podman`.
This will generate an auth file at `/run/user/1000/containers/auth.json`:

[.highside,source,bash,role=execute]
----
podman login -u init -p discopass $(hostname):8443
----

== Mirroring Content

Now we're ready to mirror images from disk into the registry.
Let's add `oc` and `oc-mirror` to the path:

[.highside,source,bash,role=execute]
----
sudo mv /mnt/high-side-data/oc /bin/
sudo mv /mnt/high-side-data/oc-mirror /bin/
----

And fire up the mirror!
Let's send it to the background with `nohup` so we can get to work on the installation prep while this is running:

[.highside,source,bash,role=execute]
----
nohup oc mirror --from=/mnt/high-side-data/mirror_seq1_000000.tar docker://$(hostname):8443 &
----

Press `ENTER` once more to get your prompt back.
The log output will be streamed to a file called `nohup.out`, and your shell will notify you when the process has been completed after 10 minutes or so.

With the final mirror now running, there are only a few steps left to prepare the cluster installation.
Let's get to it!
