= Preparing the High Side

In this lab, we'll setup the [.highside]#*highside* system#.
Recall from the architecture diagram that you will configure the [.highside]#*highside* system# to run a container image registry service inside the disconnected network.
We'll use OpenShift's `mirror-registry` utility as our image registry.
`mirror-registry` is a simplified version of Red Hat's Quay image registry.
You can use any registry you like for this as long as it supports Docker v2, such as:

* Red Hat Quay (also known as `mirror-registry`)
* JFrog Artifactory
* Sonatype Nexus Repository
* Harbor

[TIP]
The `mirror-registry` requires `podman` on the [.highside]#*highside* system#.
`podman` was installed for you.
Recall from xref:lab02.adoc[Lab 2] that the RHEL repos the provide `podman` are accessible via the `nat` system's squid proxy.

image::disco-2.svg[disco diagram,800]

== Log into the highside system

In the lab environment, you cannot log into the [.highside]#*highside* system# directly because its in a disconnected network.
Many customers access their disconnected systems using a VPN, a jump server, or a dedicated workstation.
In the lab environment you'll access the [.highside]#*highside* system# using SSH from the [.lowside]#*jump* system#.
Passwordless SSH has been enabled for your convenience.
For example, `ssh highside`

[WARNING]
Ensure that your `oc mirror` command has completed successfully before proceeding in the lab.
You can confirm the mirroring has finished by looking for ...
TODO - add the last few lines of `oc mirror`

[.lowside,source,bash,role=execute,subs="attributes"]
----
ssh highside
----

== Prove that highside is disconnected

Please use the following commands to prove that the [.highside]#*highside* system# is unable to talk to redhat.com and quay.io directly.
The OpenShift installation content is hosted at quay.io
The responses below come from the Squid proxy sevice running on the *nat* system.

Keep in mind that [.highside]#*highside*# is allowed to talk to:

* the Red Hat RPM repo inside Amazon AWS (rhui-REGION-aws.ce.redhat.com)
* the Amazon API endpoints to create Amazon EC2 instances/VMs (ec2.us-east-2.amazonaws.com)
* 🛑 nothing else 🛑

The output for a blocked website (quay.io) will look similar to this:
[.highside,source,html,role=execute]
----
curl -kI quay.io
----
[.output]
----
HTTP/1.1 403 Forbidden
Server: squid/5.5
Mime-Version: 1.0
Date: Mon, 29 Apr 2024 20:08:15 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 3434
X-Squid-Error: ERR_ACCESS_DENIED 0
----

The output for an allowed website (Red Hat RPM repos in Amazon AWS) will look similar to this:
[.highside,source,html,role=execute]
----
curl -kI https://rhui.us-east-2.aws.ce.redhat.com
----
[.output]
----
HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 29 Apr 2024 20:15:51 GMT
Content-Type: text/html
Content-Length: 4927
Last-Modified: Mon, 12 Jul 2021 19:36:32 GMT
----

== Moving the installation content into highside / the disconnected network

Let's go back to the [.lowside]#*jump* system# and beginning moving the mirrored content into the disconnected network.
The [.lowside]#*jump* system# will use `rsync` to copy the content into `/mnt/high-side-data` on the [.highside]#*highside* system#.

[TIP]
--
The `rsync` process is moving a lot of data.

This command will take about 10 minutes to complete.

Please DO NOT close the terminal while `rsync` is working.
--

[.lowside,source,bash,role=execute,subs="attributes"]
----
rsync -avP /mnt/low-side-data/ lab-user@highside:/mnt/high-side-data/
----

== Creating a Mirror Registry

Images used by operators and platform components must be mirrored from upstream sources into a container registry that is accessible by the high side.

An OpenShift subscription includes access to the https://docs.openshift.com/container-platform/4.14/installing/disconnected_install/installing-mirroring-creating-registry.html#installing-mirroring-creating-registry[mirror registry for Red Hat OpenShift], which is a small-scale container registry designed specifically for mirroring images in disconnected installations.
We'll make use of this option in this lab.

Mirroring all release and operator images can take some time depending on the network bandwidth.
For this lab, recall that we are only mirroring the release images to save time and resources.

We should have the `mirror-registry` binary along with the required container images available on [.highside]#*highside*# in `/mnt/high-side-data`.

First, let's SSH back into the [.highside]#*highside* system#:

[.lowside,source,bash,role=execute,subs="attributes"]
----
ssh lab-user@highside
----

And kick off our mirror registry install:

[.highside,source,bash,role=execute]
----
cd /mnt/high-side-data
./mirror-registry install --quayHostname $(hostname) --quayRoot /mnt/high-side-data/quay/quay-install --quayStorage /mnt/high-side-data/quay/quay-storage --pgStorage /mnt/high-side-data/quay/pg-data --initPassword discopass
----
[.output]
----
...
INFO[2023-07-06 15:43:41] Quay installed successfully, config data is stored in /mnt/quay/quay-install
INFO[2023-07-06 15:43:41] Quay is available at https://ip-10-0-51-47.ec2.internal:8443 with credentials (init, discopass)
----

Copy the CA into the root trust

[.highside,source,bash,role=execute]
----
sudo cp /mnt/high-side-data/quay/quay-install/quay-rootCA/rootCA.pem /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust
----

Login to the registry with `podman`.
This will generate an auth file at `/run/user/1000/containers/auth.json`:

[.highside,source,bash,role=execute]
----
podman login -u init -p discopass $(hostname):8443
----

== Mirroring Content

Now we're ready to mirror images from disk into the registry.
Let's add `oc` and `oc-mirror` to the path:

[.highside,source,bash,role=execute]
----
sudo mv /mnt/high-side-data/oc /bin/
sudo mv /mnt/high-side-data/oc-mirror /bin/
----

And fire up the mirror!
Let's send it to the background with `nohup` so we can get to work on the installation prep while this is running:

[.highside,source,bash,role=execute]
----
nohup oc mirror --from=/mnt/high-side-data/mirror_seq1_000000.tar docker://$(hostname):8443 &
----

Press `ENTER` once more to get your prompt back.
The log output will be streamed to a file called `nohup.out`, and your shell will notify you when the process has been completed after 10 minutes or so.

With the final mirror now running, there are only a few steps left to prepare the cluster installation.
Let's get to it!
