= Disconnected Overview

Let's start with an overview of OpenShift's disconnected installation process.
You can refer to the https://docs.openshift.com/container-platform/{openshift_version}/installing/disconnected_install/index.html[OpenShift documentation,window=_blank] for more details.

**The disconnected installation steps are:**

{counter:steps}. Prepare a system ([.lowside]#jump#) that can download the mirroring tools and the OpenShift installation images

** Use `oc-mirror` to download the content

{counter:steps}. Move the mirroring tools and installation images from the [.lowside]#jump system# to the [.highside]#highside system#

** We'll use `rsync` in this workshop
** Many people use DVDs and actually walk the content between systems and over air gaps
*** This is known as https://en.wikipedia.org/wiki/Sneakernet[👟 _sneaker net_ 👟,window=_blank]

{counter:steps}. Setup a system ([.highside]#highside#) that can _serve the installation images_ in the disconnected network

** Install the `mirror-registry`
** Use `oc-mirror` to populate the `mirror-registry`

{counter:steps}. Tell the OpenShift installation program (`openshift-install`) where to find the installation images

** Make a few changes to the default `install-config.yaml` file
*** Add the TLS certificate data for the `mirror-registry`
*** Add credentials (`pull secret`) for the `mirror-registry`
*** Add the `mirror-registry` as an approved mirror source

{counter:steps}. After OpenShift has been installed...

** Tell OpenShift where to look for apps / Operators
** Tell OpenShift where to look for updates

Now that we know the procedure, let's start with **Step 1 - Preparing the [.lowside]#jump system#**

== Preparing the `jump system`

The [.lowside]#jump system# lives in the [.lowside]#lowside network# which allows it to download the mirroring tools and installation images.
The network is called [.lowside]#lowside# because it has a low security profile, and shouldn't be used to store sensitive information.

image::disco-0.svg[disco diagram,800]

=== Download Mirroring Tools

OpenShift provides two primary tools that are used to create disconnected clusters:

{counter:tools}. `oc-mirror` - A tool to help you download:

** The OpenShift installation images (a specific set of container images)
** Additional container images such as `docker.io/wordpress`
** Individual Operators like the Web Terminal, the DISA STIG Compliance Operator, etc...
** Helm charts like `csi-driver-nfs`

{counter:tools}. `mirror-registry` - An _image registry_ that serves container images to the OpenShift nodes

** This is a https://docs.openshift.com/container-platform/{openshift_version}/installing/disconnected_install/installing-mirroring-creating-registry.html[smaller & streamlined,window=_blank] version of the Red Hat Quay Image Registry

We will also download two additional tools that will be used later on the [.highside]#highside system#.

{counter:tools}. `oc`: The OpenShift command line interface

{counter:tools}. `openshift-install`: The OpenShift Installer

[NOTE]
--
OpenShift 4.10 introduced `oc-mirror` as a new tool to download OpenShift content.
The previous tool, `oc adm release mirror ...`, is still available but not recommended.

[%hardbreaks]
`oc-mirror` allows you to download additional images, Helm charts, and individual Operators.
`oc-mirror` also intelligently downloads only the changes when updates are downloaded.
--

[NOTE]
--
Disconnected OpenShift installations can use any _image registry_ that supports the Docker v2 API, [.underline]#provide TLS encryption, and require authenticated image pulls#, such as:

* Harbor
* JFrog Artifactory
* Sonatype Nexus Repository
* Red Hat Quay Registry (enterprise)
--

Please begin by changing your directory to `/mnt/low-side-data/`
[.lowside,source,bash,role=execute,subs="attributes"]
----
cd /mnt/low-side-data/
----

[TIP]
--
Click the *Copy* button to quickly grab all of the commands in the code blocks.

On Linux, press **Ctrl + Shift + V** to paste.
Using **Ctrl + Insert** (copy) and **Shift + Insert** (paste) also works.

The pasted commands won't run immediately.
You must to hit Enter/Return yourself.
--

Use the following commands to download and extract the following tools.

* `oc-mirror`: A plugin to the `oc` command for mirorring OpenShift releases, apps / Operators, additional images, and Helm charts

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc-mirror.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_min_version}/oc-mirror.tar.gz
tar -xzf oc-mirror.tar.gz
rm -f oc-mirror.tar.gz
chmod +x oc-mirror
sudo cp -v oc-mirror /bin
----

* `mirror-registry`: a small-scale Red Hat Quay registry designed for mirroring

[.lowside,source,bash,role=execute]
----
curl -L -o mirror-registry.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/mirror-registry/latest/mirror-registry.tar.gz
----

* `oc`: The OpenShift command line interface

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_min_version}/openshift-client-linux.tar.gz
tar -xzf oc.tar.gz oc
rm -f oc.tar.gz
sudo cp -v oc /bin
----

* `openshift-install`: The OpenShift Installer

[.lowside,source,bash,role=execute,subs="attributes"]
----
curl -L -o openshift-install.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{openshift_min_version}/openshift-install-linux.tar.gz
tar -xzf openshift-install.tar.gz openshift-install
rm -f openshift-install.tar.gz
----

== Mirroring the OpenShift installation images

Now that the mirroring and installation tools have been downloaded and extracted, it's time to put `oc-mirror` to work! Let's start with a brief overview of using `oc-mirror`:

{counter:mirror}. Provide your access credentials (a **_pull secret_**)

** Credentials are required to download OpenShift installation images

{counter:mirror}. Create a YAML file that describes:

** What to download (OpenShift itself, an Operator, and an image)
** What versions (e.g. everything between {openshift_min_version} and {openshift_max_version})
** Where to store the download content

{counter:mirror}. Run `oc-mirror`

** This process downloads ~25 GB of data and takes about 15 minutes in this workshop environment
** We will run this process in the background so that you can keep working.

[NOTE]
--
A **_pull secret_** is JSON-formated data that combines authentication information for one or more Image Registries into a single file.
You can find your own _pull secret_ in the https://console.redhat.com/openshift/install/pull-secret[Red Hat Hybrid Cloud Console,window=_blank].

More information about _pull secrets_ can be found in the xref:appendix01.adoc#pull-secrets[Appendix].

This workshop provides a generic _pull secret_ in order to avoid delays and frustrations using `vi` or `nano`.
--

Please begin by copying the provided _pull secret_ into the default location.

[.lowside,source,bash,role=execute]
----
mkdir -v ~/.docker
cp -v ~/pull-secret-example.json ~/.docker/config.json
----

Next, we need to create an `ImageSetConfiguration` that describes what needs to be downloaded.
**To save time and storage, we're only going to download two versions of OpenShift**.
We will also only download one extra app/Operator, the `Web Terminal` Operator.
And one additional image, `registry.redhat.io/rhel8/support-tools`.
No Helm charts will be download.

[TIP]
--
You can find a more detailed https://gist.github.com/kincl/5a269ff3d41632588c9258090a5ea486#file-imageset-config-4-14-yaml[example of an `ImageSetConfig`,window=_blank] in this GitHub Gist.
Please don't make any changes to the provided `ImageSetConfig` because it will increase the amount of time required to download and transfer the content.
--

Create a file called `imageset-config.yaml` with the following contents:

[.lowside,source,yaml,subs="attributes",role=execute]
----
cat << EOF > imageset-config.yaml
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: {openshift_channel}
      type: ocp
      minVersion: {openshift_min_version}
      maxVersion: {openshift_max_version}

  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v{openshift_version}
    packages:
    - name: web-terminal
      channels:
      - name: fast
  
  additionalImages:
  - name: registry.redhat.io/rhel8/support-tools

  helm: {}
EOF
----

[WARNING]
--
Please run the next `oc-mirror` command in a `tmux` screen.
This will allow you to move on to the next section while `oc-mirror` downloads ~25 GB of data.

Your workshop environment has configured `tmux` to be as user-friendly as possible.

**The download takes about 15 minutes in this workshop environment.**
--

Let's create a `tmux` session and begin the `oc-mirror` download.
Run the `tmux` command and see how your terminal is automatically split into two "panes", top and bottom.
You can use your mouse to click and change between the top _pane_ and the bottom _pane_.
You can drag the line that divides the panes to resize them.

If you use your scroll wheel, please press `q` to return to the bottom and continue typing.

[TIP]
For more information on tmux, xref:appendix-tmux.adoc[check out the Appendix]

[.lowside,source,bash,role=execute]
----
tmux
----
[.output]
----
[lab-user@jump ~]$   ### This is the top pane ###



───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[lab-user@jump ~]$   ### This is the bottom pane ###



[0] 0:bash*                                                                     "ip-10-0-6-23.us-west-" 07:21 01-May-24
        Welcome to tmux - press [Ctrl + b then d] to Disconnect or press [Ctrl + b then h] for additional Help         
  Mouse mode has been turned on. Click to select your window/pane. Resize works too. Hold shift when selecting text.   
----

Now that `tmux` is running, choose one of the _panes_ to run the `oc-mirror` command.
`oc-mirror` is run with an argument to specify the `ImageSetConfig` file and the output URL.

[.lowside,source,bash,role=execute]
----
oc mirror --config imageset-config.yaml file:///mnt/low-side-data
----
[.output]
----
...
info: Mirroring completed in 2m52.23s (131.9MB/s)
Creating archive /mnt/low-side-data/mirror_seq1_000000.tar
----
